# Generated by Django 6.1 on 2026-08-16 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monthly_credits', models.PositiveIntegerField(default=25)),
                ('max_resolution', models.CharField(default='4K', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('stripe_price_id', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'price_usd'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive to add credits, negative to deduct.')),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(choices=[('signup_bonus', 'Signup bonus'), ('monthly_grant', 'Monthly plan grant'), ('demo_topup', 'Demo top-up'), ('purchase', 'Purchase'), ('job_charge', 'Job processing charge'), ('job_refund', 'Job refund (failed job)'), ('admin_adjustment', 'Admin adjustment')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='studio.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
