# Generated by Django 6.1 on 2026-08-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_plan_options_rename_price_usd_plan_price_inr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allows_video',
            field=models.BooleanField(default=True, help_text='If off, users on this plan can only enhance images, not video.'),
        ),
    ]
