# Generated by Django 6.1 on 2026-08-16 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('patch_applied', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_edit_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Turn any photo or video into 8K, cinematic quality.', max_length=160)),
                ('subheadline', models.CharField(default='Upload your media, describe what you want in plain English, and let real AI upscaling do the rest.', max_length=280)),
                ('primary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('accent_color', models.CharField(default='#3b82f6', max_length=7)),
                ('background_color', models.CharField(default='#05050a', max_length=7)),
                ('hero_autoplay', models.BooleanField(default=True)),
                ('hero_muted', models.BooleanField(default=True)),
                ('hero_loop', models.BooleanField(default=True)),
                ('cta_label', models.CharField(default='Upload & Enhance Free', max_length=40)),
                ('cta_url', models.CharField(default='/accounts/sign-up/', max_length=200)),
                ('features', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='studio.asset')),
                ('hero_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='studio.asset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
