# Generated by Django 6.1 on 2026-08-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Your display name.', max_length=150, verbose_name='display name'),
        ),
    ]
