# Generated by Django 6.1 on 2026-08-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
